// utils/errorTypes.js
export const ErrorTypes = {
  NETWORK: 'NETWORK_ERROR',
  AUTHENTICATION: 'AUTH_ERROR',
  VALIDATION: 'VALIDATION_ERROR',
  SERVER: 'SERVER_ERROR',
  MEASUREMENT: 'MEASUREMENT_ERROR',
  CAMERA: 'CAMERA_ERROR',
  CALIBRATION: 'CALIBRATION_ERROR',
  UNKNOWN: 'UNKNOWN_ERROR'
};

export const ErrorSeverity = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL'
};
